# Generated by Django 5.2.12 on 2026-03-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='link',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.author'),
        ),
    ]
